version: '3.7'

services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_DATASOURCE_URL: #jdbc:mysql://db:3306/websockets_messaging?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: #springuser
      SPRING_DATASOURCE_PASSWORD: #ThePassword
    networks:
      - backend

  # Database Service (Mysql)
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: websockets_messaging
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
